enum HTTPStatusCode {
    // Infos
    INFO_CONTINUE=100,
    INFO_SWITCHING_PROTOCOLS=101,
    INFO_PROCESSING=103,
    // Success
    SUCC_OK=200,
    SUCC_CREATED=201,
    SUCC_ACCEPTED=202,
    SUCC_NON_AUTHORATIVE_INFORMATION=203,
    SUCC_NO_CONTENT=204,
    SUCC_RESET_CONTENT=205,
    SUCC_PARTIAL_CONTENT=206,
    SUCC_MULTI_STATUS=207,
    // Redirects
    REDI_MULTIPLE_CHOICES=300,
    REDI_MOVED_PERMANENTLY=301,
    REDI_FOUND_MOVED_TEMPORARILY=302,
    REDI_SEE_OTHER=303,
    REDI_NOT_MODIFIED=304,
    REDI_USE_PROXY=305,
    // Client Errors
    CERR_BAD_REQUEST=400,
    CERR_UNAUTHORIZED=401,
    CERR_PAYMENT_REQUIRED=402,
    CERR_FORBIDDEN=403,
    CERR_NOT_FOUND=404,
    CERR_METHOD_NOT_ALLOWED=405,
    CERR_REQUEST_TIMEOUT=408,
    CERR_GONE=410,
    CERR_LOCKED=423,
    CERR_TOO_MANY_REQUESTS=429,
    CERR_IM_A_TEAPOT=418,
    // Server Errors
    SERR_INTERNAL_SERVER_ERROR=500,
    SERR_NOT_IMPLEMENTED=501,
    SERR_BAD_GATEWAY=502,
    SERR_SERVICE_UNAVAILABLE=503,
    SERR_GATEWAY_TIMEOUT=504,
    SERR_BANDWIDTH_LIMIT_EXCEEDED=510

};

export default HTTPStatusCode;